spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_service_db
    username: user
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001
server:
  port: 9001
  shutdown: graceful



bookshop:
  greeting: "Welcome to Sam Bookshop"
  testdata:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}