spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  docker:
    compose:
      file: ./docker-compose.yml
      skip:
        in-tests: true
server:
  port: 9001



bookshop:
  greeting: "Welcome to Sam Bookshop"
  testdata:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
