spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 9001


bookshop:
  greeting: "Welcome to Sam Bookshop"
  testdata:
    enabled: true
