spring:
    application:
        name: dispatcher-service
    cloud:
        function:
            definition: pack|label
        stream:
            bindings:
                packlabel-in-0:
                    destination: order-accepted
                    group: ${spring.application.name}
                packlabel-out-0:
                    destination: order-dispatched
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
server:
    port: 9003

management:
    endpoints:
        web:
            exposure:
                include: refresh,health
    endpoint:
        health:
            show-details: always
            show-components: always
            probes:
                enabled: true
    metrics:
        tags:
            application: ${spring.application.name}