# build
custom_build(
     # Name of the container image
     ref = 'config-server',
     # Build container image
     command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
     # Files to watch that trigger a new build
     deps = ['build.gradle', 'src']
)

# deploy
k8s_yaml(['k8s/deployment.yaml', 'k8s/service.yaml'])

# Manage
k8s_resource('config-server', port_forwards=['8888'])
