apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
              protocol: TCP
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://bookshop-postgres/order_service_db
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://bookshop-postgres/order_service_db
            - name: CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092

