spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/order_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/order_service_db

  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        acceptOrder-out-0:
          destination: order-accepted
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

bookshop:
  catalog-service-uri: "http://localhost:9001"
