apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: bookshop-postgres
data:
  init.sql: |
    CREATE DATABASE catalog_service_db;
    CREATE DATABASE order_service_db;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-postgres
  labels:
    db: bookshop-postgres
spec:
  selector:
    matchLabels:
      db: bookshop-postgres
  template:
    metadata:
      labels:
        db: bookshop-postgres
    spec:
      containers:
        - name: bookshop-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: bookshop-postgres
  labels:
    db: bookshop-postgres
spec:
  type: ClusterIP
  selector:
    db: bookshop-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432