name: commit-stage
on: push
env:
  REGISTRY: ghcr.io
  VERSION: ${{ github.sha }}
  JAVA_VERSION: 17

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        service: [catalog-service,config-server]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.1.3
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle
      - name: Build, unit test, and Integration Test
        run: |
          chmod +x gradlew
          ./gradlew :${{ matrix.service }}:build
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    strategy:
      matrix:
        service: [catalog-service,config-server]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.1.3
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle
      - name: Build container image
        run: |
          chmod +x gradlew
          ./gradlew :${{ matrix.service }}:bootBuildImage \
            --imageName ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.service }}:${{ env.VERSION }}
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container Image
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.service }}:${{ env.VERSION }}
      - name:  Publish container image
        run: |
          docker tag ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.service }}:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.service }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.service }}:latest
 
